In [1]:
%load_ext autoreload
%autoreload

In [2]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
import data_creation as dc 

In [3]:
train_data = np.array([[1.0,1.0]])
train_targets = np.array([2.0])

In [4]:
train_data

array([[1., 1.]])

In [5]:
train_targets

array([2.])

In [6]:
for i in range(3,10000,2):
    train_data=np.append(train_data, [[i,i]],axis=0)
    train_targets=np.append(train_targets,[i+i])
test_data = np.array([[2.0,2.0]])
test_targets = np.array([4.0])
for i in range(4,8000,4):
    test_data = np.append(test_data,[[i,i]],axis=0)
    test_targets=np.append(test_targets,[i+i])

In [7]:
test_data.shape

(2000, 2)

In [8]:
test_targets.shape

(2000,)

In [9]:
test = np.array(test_data)

In [10]:
test

array([[2.000e+00, 2.000e+00],
       [4.000e+00, 4.000e+00],
       [8.000e+00, 8.000e+00],
       ...,
       [7.988e+03, 7.988e+03],
       [7.992e+03, 7.992e+03],
       [7.996e+03, 7.996e+03]])

In [11]:
df = pd.DataFrame(test)

In [12]:
df

0       1
0        2.0     2.0
1        4.0     4.0
2        8.0     8.0
3       12.0    12.0
4       16.0    16.0
...      ...     ...
1995  7980.0  7980.0
1996  7984.0  7984.0
1997  7988.0  7988.0
1998  7992.0  7992.0
1999  7996.0  7996.0

[2000 rows x 2 columns]

In [13]:
df = pd.DataFrame(train_data)

In [14]:
df

0       1
0        1.0     1.0
1        3.0     3.0
2        5.0     5.0
3        7.0     7.0
4        9.0     9.0
...      ...     ...
4995  9991.0  9991.0
4996  9993.0  9993.0
4997  9995.0  9995.0
4998  9997.0  9997.0
4999  9999.0  9999.0

[5000 rows x 2 columns]

In [15]:
df = pd.DataFrame(train_targets)

In [16]:
df

0
0         2.0
1         6.0
2        10.0
3        14.0
4        18.0
...       ...
4995  19982.0
4996  19986.0
4997  19990.0
4998  19994.0
4999  19998.0

[5000 rows x 1 columns]

In [30]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(2,)),
    keras.layers.Dense(32, activation=tf.nn.relu),
	keras.layers.Dense(64, activation=tf.nn.relu),
    keras.layers.Dense(1)
])

In [31]:
model.compile(optimizer='adam',
             loss='mse',
             metrics=['mae'])

In [32]:
model.fit(dc.train_data, dc.train_targets, epochs=10, batch_size=1)

Epoch 1/10
5000/5000 [==============================] - 4s 739us/step - loss: 578966.5000 - mae: 71.0121
Epoch 2/10
5000/5000 [==============================] - 4s 735us/step - loss: 7713.7593 - mae: 21.9135
Epoch 3/10
5000/5000 [==============================] - 4s 739us/step - loss: 2151.5696 - mae: 11.4395
Epoch 4/10
5000/5000 [==============================] - 4s 756us/step - loss: 3333.1287 - mae: 12.2605
Epoch 5/10
5000/5000 [==============================] - 4s 749us/step - loss: 4069.0383 - mae: 15.0670
Epoch 6/10
5000/5000 [==============================] - 4s 754us/step - loss: 5131.2061 - mae: 15.2950
Epoch 7/10
5000/5000 [==============================] - 4s 755us/step - loss: 2858.6956 - mae: 11.0288
Epoch 8/10
5000/5000 [==============================] - 4s 885us/step - loss: 3617.3132 - mae: 17.0941
Epoch 9/10
5000/5000 [==============================] - 4s 778us/step - loss: 5280.2578 - mae: 13.0299
Epoch 10/10
5000/5000 [==============================] - 4s 771us/step 

In [33]:
test_loss, test_acc = model.evaluate(dc.test_data, dc.test_targets)

63/63 [==============================] - 0s 1ms/step - loss: 110906.2031 - mae: 288.3526


In [34]:
print('Test accuracy:', test_acc)

Test accuracy: 288.3525695800781


In [35]:
a= np.array([[2000,3000],[4,5]])

In [36]:
model.predict(a)

array([[4748.8003 ],
       [   8.70375]], dtype=float32)

#### Conclusion

It is to be noted that the example we have used, i.e. Addition of two numbers, is just for indicative purpose and it is not the best use of neural networks. However, it is easy to understand and develop an intuitive understanding of neural networks and how a traditional computational problem, such as Addition, can be handled in the Deep Learning world. Deep learning is a black box based model of problem-solving, so the results change with the different parameters. The user needs to get familiarized with the different parameters and how to play around with them to develop an intuitive understanding of what parameters work for a problem at hand. The more a user practices deep learning and works with different problems, the better the understanding she is going to develop.