In [11]:
import keyword

In [12]:
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [13]:
len(keyword.kwlist)

35

In [14]:
a = 20
print(a, "is of type", type(a))

20 is of type <class 'int'>


In [15]:
"""This is a course on Machine Learning and Artificial Intelligence"""

'This is a course on Machine Learning and Artificial Intelligence'

In [16]:
a = ['boy', 4, 5, 6, 'well']
a[1]

4

In [17]:
a[1] += 10

In [18]:
a

['boy', 14, 5, 6, 'well']

In [19]:
a = ('boy', 4, 5, 6, 'well')

In [21]:
a = {'boy', 4, 5, 6, 'well'}

In [22]:
a

{4, 5, 6, 'boy', 'well'}

In [27]:
type(3)

int

In [28]:
a = "Boyo"
b= 30
c= "wicked producer"

In [29]:
print("the boy is named {} and he is {} years old".format(a,b))

the boy is named Boyo and he is 30 years old


In [30]:
a = "Bayo"
b= 30
c= "wicked producer"

In [31]:
print("Mr {0} who has been in business for {1}years is a {2} ".format(a,b,c))

Mr Bayo who has been in business for 30years is a wicked producer 


In [32]:
a = [12,4,56,7,89,10,25]

In [33]:
len(a)

7

In [34]:
def product(x: list)-> int:
    index = 0 
    product = 1
    
    while index < len(x):
        product *= x[index]
        index += 1
        
    return product

In [35]:
print(product(a))

418656000


In [36]:
def prime(number: int)-> int:
    
    i = 2
    has_factor = False
    
    while i < number :
        if number%i == 0:
            has_factor = True
            print("{} is a factor of {}".format(i, number))
        i += 1
    
    if has_factor:
        print("{} is not a prime number".format(number))
    else:
        print("{} is a prime number".format(number))
        


In [37]:
prime(150)

2 is a factor of 150
3 is a factor of 150
5 is a factor of 150
6 is a factor of 150
10 is a factor of 150
15 is a factor of 150
25 is a factor of 150
30 is a factor of 150
50 is a factor of 150
75 is a factor of 150
150 is not a prime number


In [38]:
def product(x: list)-> int:
    
    product = 1
    
    for num in x:
        product *= num
       
        
    return product

In [39]:
product(a)

418656000

In [40]:
def prime(number: int)-> int:
    
    has_factor = False
    
    for i in range (2, number):
        if number%i == 0:
            has_factor = True
            print("{} is a factor of {}".format(i, number))
      
    
    if has_factor:
        print("{} is not a prime number".format(number))
    else:
        print("{} is a prime number".format(number))
        


In [41]:
prime(200)

2 is a factor of 200
4 is a factor of 200
5 is a factor of 200
8 is a factor of 200
10 is a factor of 200
20 is a factor of 200
25 is a factor of 200
40 is a factor of 200
50 is a factor of 200
100 is a factor of 200
200 is not a prime number


In [42]:
a = 10
b = 50

for number in range(a, b+1):
    if number > 1:
        has_factor = False
        for index in range(2, number):
            if number % index == 0:
                has_factor = True
            if not has_factor:
                print(number)

11
11
11
11
11
11
11
11
11
13
13
13
13
13
13
13
13
13
13
13
15
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
21
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
25
25
25
27
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
33
35
35
35
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
39
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
45
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
49
49
49
49
49


In [43]:
#to print the sqaures of all numer between 0-10

square =[]

for i in range(10):
    square.append(i**2)
print(square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [44]:
square = [ i**2 for i in range(10)]

In [45]:
square

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [46]:
new_lst = [(x, x**2) for x in range(10)]

In [47]:
new_lst

[(0, 0),
 (1, 1),
 (2, 4),
 (3, 9),
 (4, 16),
 (5, 25),
 (6, 36),
 (7, 49),
 (8, 64),
 (9, 81)]

In [48]:
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

transposed = []
for i in range(4):
    lst = []
    for row in matrix:
        lst.append(row[i])
    transposed.append(lst)
print(transposed)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [49]:
transposed = [[row[i] for row in matrix] for i in range(4)]

In [50]:
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [51]:
d = {}
dir(d)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [52]:
a = []
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [53]:
def print_name(name:str)->str:
    """
    this print name
    """
    print("Hello " + str(name))

In [54]:
print_name("Fresho")

Hello Fresho


In [55]:
def list_sum(myList: list)->int:
    """
    This function take a list and return int
    """
    total = 0
    for num in myList:
        total +=num
    return total



In [56]:
list_sum.__doc__

'\n    This function take a list and return int\n    '

In [57]:
a = [2,3,4,5,6,7,8,9,10]

In [58]:
list_sum(a)

54

In [59]:
x=0
total = [(x, x+num) for num in a]

In [60]:
total

[(0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10)]

In [61]:
total = [(x+num) for num in a]

In [62]:
total

[2, 3, 4, 5, 6, 7, 8, 9, 10]

In [63]:
total = sum(a)

In [64]:
total

54

In [65]:
total = [(num+num) for num in a]

In [66]:
total

[4, 6, 8, 10, 12, 14, 16, 18, 20]

In [67]:
i =0

In [68]:
total = [(num+num[i]) for num in a]

TypeError: 'int' object is not subscriptable

In [69]:
def hcf(a,b:tuple)->int:
    """
    Computing the hcf of two numbers
    """
   
    smaller = b if a >b else a 
    hcf =1
    for i in range(1, smaller+1):
        if (a%i==0) and (b%i==0):
            hcf=i
    return hcf

In [70]:
a = 45
b= 20

In [71]:
hcf(a,b)

5

In [72]:
hcf.__doc__

'\n    Computing the hcf of two numbers\n    '

In [73]:
for index, num in enumerate(total):
    print(total)

[4, 6, 8, 10, 12, 14, 16, 18, 20]
[4, 6, 8, 10, 12, 14, 16, 18, 20]
[4, 6, 8, 10, 12, 14, 16, 18, 20]
[4, 6, 8, 10, 12, 14, 16, 18, 20]
[4, 6, 8, 10, 12, 14, 16, 18, 20]
[4, 6, 8, 10, 12, 14, 16, 18, 20]
[4, 6, 8, 10, 12, 14, 16, 18, 20]
[4, 6, 8, 10, 12, 14, 16, 18, 20]
[4, 6, 8, 10, 12, 14, 16, 18, 20]


In [74]:
def get_positive(num):
    if num>0:
        return num
    
number_list = range(-5,6)
number_list

range(-5, 6)

In [75]:
print(list(number_list))

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]


In [76]:
positive_num = list(filter(get_positive, number_list))

In [77]:
positive_num

[1, 2, 3, 4, 5]

In [78]:
lst = [1,2,3,4]
print(isinstance(lst,list))

True


In [79]:
num = [1,2,3,4,5]

squared = []
for number in num:
    square = number ** 2
    squared.append(square)
print(squared)

[1, 4, 9, 16, 25]


In [80]:
squared =[number**2 for number in num]

In [81]:
squared

[1, 4, 9, 16, 25]

In [82]:
pow(2,2)

4

In [83]:
def power(num):
    return pow(num, 2)

In [84]:
square = list(map(power, num))

In [85]:
square

[1, 4, 9, 16, 25]

In [86]:
from functools import reduce

In [87]:
def multiply(x,y):
    return x*y;



In [88]:
product = reduce(multiply, num)

In [89]:
product

120

In [14]:
class TwoNumberCalculator:
    
    def collectValues(self):
        """This function collect values"""
        
        print("Press one of these numbers to show the operation to perform")
        print("Press 1 for addition")
        print("Press 2 for subtraction")
        print("Press 3 for division")
        print("Press 4 for multiplication")
        
        choice = int(input("enter your option: "))

        a = print(float(input("Enter the first number: ")))
        b = print(float(input("Enter the second number: ")))
        
    
    def add(self):
        """This add up two numbers"""
        @collectValues()
        return a + b
    
    def subtract(self):
        """This subtract two numbers from each other"""
        @collectValues
        return a - b
  
    def divide():
        """this divide two numbers"""
        @collectValues
        return a / b
 
    def product():
        """This multiply two numbers"""
        @collectValues
        return a * b
    
    def compute():
        """This function performs the operation specified"""
        if choice == 1:
            print("{} + {} = {}".format(a,b,add(a,b)) )

        if choice == 2:
            print("{} + {} = {}".format(a,b,subtract(a,b)) )

        if choice == 3:
            print("{} + {} = {}".format(a,b,divide(a,b)) )

        if choice == 4:
            print("{} + {} = {}".format(a,b,product(a,b)) )
            

SyntaxError: invalid syntax (<ipython-input-14-cde563ad6d2d>, line 21)

In [12]:
ans = TwoNumberCalculator()
print(ans.add())

NameError: name 'TwoNumberCalculator' is not defined

In [3]:
f = open('test.txt', 'w')
f.write("What will be will be, whetor nother you like it")

f.close()

In [4]:
f = open('test.txt', 'r')
f.read()

'What will be will be, whetor nother you like it'

In [7]:
f = open('test.txt', 'r')
f.read(4)

''

In [6]:
f.read(10)

''

In [8]:
f.tell()

47

In [9]:
f.seek(0)

0

In [10]:
f.seek(0)
for line in f:
    print(line)
    

What will be will be, whetor nother you like it


In [16]:
import os

In [17]:
os.getcwd()

'/home/wizardcalidad/January'

In [11]:
ans = TwoNumberCalculator()
print(ans.collectValues(1,2))

NameError: name 'TwoNumberCalculator' is not defined

In [12]:
ans.divide(4,32)

NameError: name 'ans' is not defined

In [93]:
def greet(*names:str)->str:

    for name in names:
        print("hi" + name)
        

In [94]:
people =("ade, Bolu,bola")

In [95]:
greet(people)

hiade, Bolu,bola


In [96]:
def factorial(num):
    """
    This is a recursive function that calls itself
    """
    return 1 if num==1 else (num * factorial(num-1))

num = 5

print("Factorial of {} is {}".format(num, factorial(num)))

Factorial of 5 is 120


In [97]:
def fibonacci(num):
    """Fibonacci sequence"""
    return num if num <= 1 else fibonacci(num-1) + fibonacci(num-2)
n = 10
print("Fibonacci Sequence")
for num in range(n):
    print(fibonacci(num))

Fibonacci Sequence
0
1
1
2
3
5
8
13
21
34


In [98]:
double = lambda x : x*2

In [99]:
double(4)

8

In [101]:
a = [1,2,3,4,5,6,7,8,9,10]

even_a = list(filter(lambda x : (x%2==0), a))

In [102]:
even_a

[2, 4, 6, 8, 10]

In [103]:
odd_a = list(filter(lambda x : (x%2==1), a))

In [104]:
odd_a

[1, 3, 5, 7, 9]

In [105]:
from functools import reduce

In [107]:
b = [1,2,3,4,5]
square = list(map(lambda x: x**2, b))

In [108]:
square

[1, 4, 9, 16, 25]

In [109]:
product = reduce(lambda x, y: x*y, a)

In [110]:
product

3628800

In [18]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [20]:
try:
    num = int(input("Enter a positive integer: "))
    if num <= 0:
        raise ValueError("Error:Entered negative number")
except ValueError as e:
    print(e)

Enter a positive integer:  a


invalid literal for int() with base 10: 'a'


In [26]:
def seq(n):
    for i in range(n):
        print(i)
seq(5)   

0
1
2
3
4


In [ ]:
import pdb

def seq(n):
    for i in range(n):
        pdb.set_trace()
        print(i)
seq(5)   

> <ipython-input-27-ea036795e048>(6)seq()
      3 def seq(n):
      4     for i in range(n):
      5         pdb.set_trace()
----> 6         print(i)
      7 seq(5)



ipdb>  list


      1 import pdb
      2 
      3 def seq(n):
      4     for i in range(n):
      5         pdb.set_trace()
----> 6         print(i)
      7 seq(5)



ipdb>  p i


0


ipdb>  p n


5


ipdb>  p locals


<built-in function locals>


ipdb>  


<built-in function locals>


ipdb>  p locals()


{'n': 5, 'i': 0}


ipdb>  h



Documented commands (type help <topic>):
EOF    cl         disable  interact  next    psource  rv           undisplay
a      clear      display  j         p       q        s            unt      
alias  commands   down     jump      pdef    quit     skip_hidden  until    
args   condition  enable   l         pdoc    r        source       up       
b      cont       exit     list      pfile   restart  step         w        
break  continue   h        ll        pinfo   return   tbreak       whatis   
bt     d          help     longlist  pinfo2  retval   u            where    
c      debug      ignore   n         pp      run      unalias    

Miscellaneous help topics:
exec  pdb



In [1]:
!pip install numpy

  Using cached numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)


In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3])

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a = np.random.randn(10)

In [6]:
a

array([-0.08370703, -1.04413192, -0.04304875, -2.25358188, -0.69427304,
       -0.3441811 , -0.66914401, -0.90932207, -0.28328178,  0.76688193])

In [7]:
a = np.arange(10)

In [8]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.dtype

dtype('int64')

In [11]:
a = np.arange(10,2)

In [12]:
a

array([], dtype=int64)

In [13]:
a = np.arange(10, dtype='float')

In [14]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
a = np.zeros((3,3))

In [16]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a = np.eye(3)

In [19]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
a = np.diag([1,2,3])

In [21]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
a = np.diag([1,2,3,4])

In [23]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
a[2][3]

0

In [25]:
a[2][3] = 6

In [26]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 6],
       [0, 0, 0, 4]])

In [27]:
a = np.arange(15)

In [28]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
a[1:8:3]

array([1, 4, 7])

In [31]:
a[2:12:2]

array([ 2,  4,  6,  8, 10])

In [32]:
b = np.arange(5)

In [36]:
b

array([0, 1, 2, 3, 4])

In [35]:
 b[::-1]

array([4, 3, 2, 1, 0])

In [37]:
a = np.arange(10)

In [38]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b = a[::2]

In [40]:
b

array([0, 2, 4, 6, 8])

In [41]:
np.shares_memory(a,b)

True

In [42]:
b[0] = 10

In [43]:
b

array([10,  2,  4,  6,  8])

In [44]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [45]:
c = a[::2].copy()

In [46]:
c

array([10,  2,  4,  6,  8])

In [47]:
a = np.random.randint(0,20,15)

In [48]:
a

array([16,  6, 11,  4, 14,  8,  2,  9,  7,  4, 10, 10,  5,  1,  7])

In [49]:
a = np.random.randint(0,10,20)

In [50]:
a

array([3, 1, 7, 5, 1, 7, 2, 0, 7, 4, 5, 9, 6, 1, 8, 9, 0, 0, 1, 8])

In [51]:
mask = (a % 2 ==0)

In [52]:
mask

array([False, False, False, False, False, False,  True,  True, False,
        True, False, False,  True, False,  True, False,  True,  True,
       False,  True])

In [55]:
from_a = a[mask]

In [56]:
from_a

array([2, 0, 4, 6, 8, 0, 0, 8])

In [59]:
a[mask] = 6

In [60]:
a

array([3, 1, 7, 5, 1, 7, 6, 6, 7, 6, 5, 9, 6, 1, 6, 9, 6, 6, 1, 6])

In [61]:
a = np.arange(0, 100, 10)

In [62]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
a[[2,3,4,2,5]]

array([20, 30, 40, 20, 50])

In [65]:
a[[9,7]] = -200

In [66]:
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])